-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE,'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;