-- SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
-- FROM REST_INFO
-- WHERE (FOOD_TYPE, FAVORITES) IN
-- (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
-- ORDER BY FOOD_TYPE DESC;

-- 윈도우 함수
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) RANK
    FROM REST_INFO
) 
WHERE RANK = 1
ORDER BY FOOD_TYPE DESC;