-- 코드를 입력하세요
-- 사용자의 사용자 ID, 닉네임, 전체주소, 전화번호
SELECT 
    B.USER_ID,
    B.NICKNAME,
    B.CITY||' '||B.STREET_ADDRESS1||' '||B.STREET_ADDRESS2 전체주소,
    SUBSTR(B.TLNO,1,3)||'-'||SUBSTR(B.TLNO,4,4)||'-'||SUBSTR(B.TLNO,8,4) 전화번호
    
-- FROM USED_GOODS_BOARD A
-- JOIN USED_GOODS_USER B
-- ON A.WRITER_ID = B.USER_ID

FROM USED_GOODS_USER B

WHERE B.USER_ID IN (
SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)
ORDER BY B.USER_ID DESC;