-- 코드를 입력하세요
SELECT 
    EXTRACT(YEAR FROM SALES_DATE) YEAR,
    EXTRACT(MONTH FROM SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT(I.USER_ID)) USERS

FROM USER_INFO I 
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID

WHERE I.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE),
    EXTRACT(MONTH FROM SALES_DATE),
    GENDER
    
ORDER BY YEAR, MONTH, GENDER;