-- -- 코드를 입력하세요
-- WITH TEMP AS (
-- SELECT COUNT(*)
--     FROM USER_INFO 
-- WHERE TO_CHAR(JOINED,'YYYY') = '2021'
-- )

-- -- SELECT * FROM TEMP

-- -- SELECT * FROM TEMP

-- SELECT
--     EXTRACT(YEAR FROM O.SALES_DATE) YEAR,
--     EXTRACT(MONTH FROM O.SALES_DATE) MONTH,
--     -- COUNT(DISTINCT(O.USER_ID)) USERCOUNT
--     COUNT(
--         O.USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')
--         )
    
-- --     COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*)
-- --     FROM USER_INFO 
-- -- WHERE TO_CHAR(JOINED,'YYYY') = '2021')

-- FROM ONLINE_SALE O
-- LEFT JOIN USER_INFO I
-- ON O.USER_ID = I.USER_ID

-- -- WHERE TO_CHAR(I.JOINED,'YYYY') = '2021'
-- GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), O.USER_ID
-- ORDER BY YEAR, MONTH;




WITH TEMP AS (
  SELECT COUNT(*) AS USER_COUNT
  FROM USER_INFO 
  WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)

SELECT
  EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
  EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
  COUNT(DISTINCT CASE WHEN I.USER_ID IS NOT NULL THEN O.USER_ID END) AS USER_COUNT,
  
  ROUND((COUNT(DISTINCT CASE WHEN I.USER_ID IS NOT NULL THEN O.USER_ID END) / 
  (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')),1) PUCHASED_RATIO
  
FROM ONLINE_SALE O
LEFT JOIN USER_INFO I ON O.USER_ID = I.USER_ID
WHERE TO_CHAR(I.JOINED, 'YYYY') = '2021'
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY YEAR, MONTH;
