-- 코드를 입력하세요
SELECT S.NAME, S.DATETIME
FROM (
SELECT 
    I.NAME, I.DATETIME,
    ROW_NUMBER() OVER (ORDER BY I.DATETIME ASC) AS RN
    FROM
    ANIMAL_INS I
    LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY I.DATETIME ASC
) S
WHERE RN <= 3

