WITH TRUCK AS (
    SELECT 
    C.CAR_TYPE,
    H.HISTORY_ID,
    C.DAILY_FEE, 
    CASE 
        WHEN (H.END_DATE - H.START_DATE + 1) >= 90 THEN '90일 이상'
        WHEN (H.END_DATE - H.START_DATE + 1) >= 30 THEN '30일 이상'
        WHEN (H.END_DATE - H.START_DATE + 1) >= 7 THEN '7일 이상'
        ELSE NULL
    END AS DURATION_TYPE,
    (H.END_DATE - H.START_DATE + 1) AS 대여일
    
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    T.HISTORY_ID HISTORY_ID,
    CASE 
        WHEN T.DURATION_TYPE IS NULL THEN T.DAILY_FEE * T.대여일
        ELSE ROUND((T.DAILY_FEE * (1 - (P.DISCOUNT_RATE/100))) * T.대여일) 
    END AS FEE 
FROM TRUCK T
LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭') P
ON T.DURATION_TYPE = P.DURATION_TYPE

ORDER BY FEE DESC, HISTORY_ID DESC;