WITH RECURSIVE TEMP AS(
SELECT 0 AS HOUR
UNION
SELECT HOUR + 1
FROM TEMP
WHERE HOUR < 23
)

SELECT TEMP.HOUR, COUNT(ANIMAL_OUTS.ANIMAL_ID) AS COUNT
FROM TEMP
LEFT JOIN ANIMAL_OUTS
ON TEMP.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY TEMP.HOUR
ORDER BY TEMP.HOUR;