WITH TEMPHOUR AS (
SELECT 
    LEVEL - 1 HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
),
TEMPCOUNT AS (
SELECT
    TO_CHAR(DATETIME, 'HH24') HOUR,
    COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
)

SELECT H.HOUR, NVL(C.COUNT,0)
FROM TEMPHOUR H
LEFT JOIN TEMPCOUNT C
ON H.HOUR = C.HOUR
ORDER BY H.HOUR ASC;
