WITH TEMP AS (
SELECT CAR.DAILY_FEE, CAR.CAR_TYPE, HIS.HISTORY_ID,
    DATEDIFF(HIS.END_DATE,HIS.START_DATE) + 1 AS PERIOD,
    CASE
    WHEN DATEDIFF(HIS.END_DATE,HIS.START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(HIS.END_DATE,HIS.START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(HIS.END_DATE,HIS.START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE 'NONE'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
JOIN CAR_RENTAL_COMPANY_CAR CAR
ON HIS.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_TYPE = '트럭')

SELECT TEMP.HISTORY_ID, 
ROUND(
    TEMP.DAILY_FEE * TEMP.PERIOD * 
    (100 - IFNULL(PLAN.DISCOUNT_RATE,0)) / 100
) AS FEE
FROM TEMP
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON TEMP.DURATION_TYPE = PLAN.DURATION_TYPE
AND TEMP.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY FEE DESC, TEMP.HISTORY_ID DESC ;
    