-- 코드를 입력하세요
SELECT 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR,
    COUNT(*) COUNT
FROM 
    ANIMAL_OUTS 
GROUP BY 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 20
    
ORDER BY HOUR;
