-- 코드를 입력하세요

WITH COUNTS AS (
SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEWS
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (SELECT MAX(COUNT(MEMBER_ID)) FROM REST_REVIEW GROUP BY MEMBER_ID)
ORDER BY REVIEWS DESC
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, 
TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID FROM COUNTS)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;