-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS SALES_DATE
FROM BOOK B
JOIN BOOK_SALES S USING(BOOK_ID)
# WHERE S.SALES_DATE LIKE "2022-01%"
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;