-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE MAX_PRICE, F.PRODUCT_NAME
FROM (SELECT 
    CATEGORY,
    PRODUCT_NAME,
      PRICE,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
     ) F
WHERE PRICE_RANK = 1
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
